<?php


//This is the access privilege file
$is_admin=true;

$user_info=array('user_name'=>'admin','is_admin'=>'on','user_password'=>'$2y$10$.FAiMwmuOwxCXbmEr/kcceIGoYdg15vMtqwnp/g9FiQVJKLczPo2W','confirm_password'=>'$2y$10$.FAiMwmuOwxCXbmEr/kcceIGoYdg15vMtqwnp/g9FiQVJKLczPo2W','first_name'=>'Kalpesh','last_name'=>'Vaza','roleid'=>'H2','email1'=>'kalpesh@biztechnosys.com','status'=>'Active','activity_view'=>'Today','lead_view'=>'Today','hour_format'=>'24','end_hour'=>'23:00','start_hour'=>'08:00','is_owner'=>'1','title'=>'','phone_work'=>'','department'=>'','phone_mobile'=>'','reports_to_id'=>'','phone_other'=>'','email2'=>'','phone_fax'=>'','secondaryemail'=>'','phone_home'=>'','date_format'=>'dd-mm-yyyy','signature'=>'&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.2;text-align:justify;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:rgb(80,0,80);font-family:Arial, Helvetica, sans-serif;font-size:small;background-color:rgb(255,255,255);&quot;&gt;&lt;span style=&quot;font-size:12pt;font-family:Georgia;color:rgb(0,0,0);background-color:transparent;font-weight:700;vertical-align:baseline;white-space:pre-wrap;&quot;&gt;Thanks &amp; Regards,&lt;/span&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.2;text-align:justify;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:rgb(80,0,80);font-family:Arial, Helvetica, sans-serif;font-size:small;background-color:rgb(255,255,255);&quot;&gt;&lt;span style=&quot;font-size:12pt;font-family:Georgia;color:rgb(0,0,0);background-color:transparent;font-weight:700;vertical-align:baseline;white-space:pre-wrap;&quot;&gt;Lokesh S | &lt;/span&gt;&lt;b style=&quot;color:rgb(34,34,34);font-family:georgia, serif;&quot;&gt;Software Engineer&lt;/b&gt;&lt;/span&gt;&lt;/p&gt;

&lt;p dir=&quot;ltr&quot; style=&quot;line-height:1.2;text-align:justify;margin-top:0pt;margin-bottom:0pt;&quot;&gt;&lt;span style=&quot;color:rgb(80,0,80);font-family:Arial, Helvetica, sans-serif;font-size:small;background-color:rgb(255,255,255);&quot;&gt;&lt;span style=&quot;font-size:12pt;font-family:Georgia;color:rgb(0,0,0);background-color:transparent;font-weight:700;vertical-align:baseline;white-space:pre-wrap;&quot;&gt;+91 &lt;/span&gt;&lt;span style=&quot;color:rgb(34,34,34);&quot;&gt;&lt;b&gt;8792760328&lt;/b&gt;&lt;/span&gt;&lt;span style=&quot;background-color:transparent;font-size:12pt;font-family:Georgia;color:rgb(0,0,0);font-weight:700;vertical-align:baseline;white-space:pre-wrap;&quot;&gt;| &lt;/span&gt;&lt;a href=&quot;http://www.biztechnosys.com/&quot; style=&quot;color:rgb(17,85,204);&quot;&gt;&lt;span style=&quot;font-size:12pt;font-family:Georgia;color:rgb(5,99,193);background-color:transparent;font-weight:700;vertical-align:baseline;white-space:pre-wrap;&quot;&gt;www.biztechnosys.com&lt;/span&gt;&lt;/a&gt;&lt;/span&gt;&lt;/p&gt;

&lt;div&gt;&lt;/div&gt;','description'=>'','address_street'=>'','address_city'=>'','address_state'=>'','address_postalcode'=>'','address_country'=>'','accesskey'=>'7k5oPdIA5OWAPGsJ','time_zone'=>'Asia/Kolkata','currency_id'=>'2','currency_grouping_pattern'=>'123,456,789','currency_decimal_separator'=>'.','currency_grouping_separator'=>',','currency_symbol_placement'=>'$1.0','imagename'=>'','internal_mailer'=>'1','theme'=>'alphagrey','language'=>'en_us','reminder_interval'=>'1 Minute','phone_crm_extension'=>'','no_of_currency_decimals'=>'2','truncate_trailing_zeros'=>'0','dayoftheweek'=>'Monday','callduration'=>'5','othereventduration'=>'5','calendarsharedtype'=>'public','default_record_view'=>'Detail','leftpanelhide'=>'0','rowheight'=>'','defaulteventstatus'=>'Planned','defaultactivitytype'=>'Call','hidecompletedevents'=>'0','defaultcalendarview'=>'MyCalendar','defaultlandingpage'=>'Home','userlabel'=>'Kalpesh Vaza','currency_name'=>'India, Rupees','currency_code'=>'INR','currency_symbol'=>'₹','conv_rate'=>'70.00000','record_id'=>'','record_module'=>'','id'=>'1');

?>