<?php


//This is the access privilege file
$is_admin=true;

$user_info=array('user_name'=>'Abdul Samad KM','is_admin'=>'on','user_password'=>'$2y$10$DrlRpLV17mUOfY3cercr0uDPUrvkIQTTO1QBsNRU2S/hHT0J0oboO','confirm_password'=>'$2y$10$JyOASUBl7B2dqY8SSxwLZeXIIilEokTl1B1pZdBBaeILAKAlxT6vy','first_name'=>'','last_name'=>'Abdul Samad KM','roleid'=>'H18','email1'=>'abdul.s@biztechnosys.com','status'=>'Active','activity_view'=>'Today','lead_view'=>'Today','hour_format'=>'12','end_hour'=>'','start_hour'=>'09:00','is_owner'=>'','title'=>'Abdul Samad KM','phone_work'=>'','department'=>'lead generation executive','phone_mobile'=>'9995723198','reports_to_id'=>'','phone_other'=>'','email2'=>'abdulsamad20@gmail.com','phone_fax'=>'','secondaryemail'=>'','phone_home'=>'9567673724','date_format'=>'yyyy-mm-dd','signature'=>'','description'=>'','address_street'=>'Samad manzil opst kidoor-671321 kasaragod Kerala  
                              &amp;
current address; #302 7th cross Marathi nagar BTM 1st stage Bangalo','address_city'=>'Bangalore','address_state'=>'Karnataka','address_postalcode'=>'560076','address_country'=>'India','accesskey'=>'6GFuCkYOAIkY248Y','time_zone'=>'UTC','currency_id'=>'2','currency_grouping_pattern'=>'123,456,789','currency_decimal_separator'=>'.','currency_grouping_separator'=>',','currency_symbol_placement'=>'$1.0','imagename'=>'','internal_mailer'=>'0','theme'=>'softed','language'=>'en_us','reminder_interval'=>'','phone_crm_extension'=>'','no_of_currency_decimals'=>'2','truncate_trailing_zeros'=>'0','dayoftheweek'=>'Sunday','callduration'=>'5','othereventduration'=>'5','calendarsharedtype'=>'public','default_record_view'=>'Detail','leftpanelhide'=>'0','rowheight'=>'medium','defaulteventstatus'=>'','defaultactivitytype'=>'','hidecompletedevents'=>'0','defaultcalendarview'=>'','defaultlandingpage'=>'Home','userlabel'=>'','currency_name'=>'India, Rupees','currency_code'=>'INR','currency_symbol'=>'₹','conv_rate'=>'70.00000','record_id'=>'','record_module'=>'','id'=>'99');

?>